/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HighlightedText: typeof import('./components/HighlightedText.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    PixelarticonsPower: typeof import('~icons/pixelarticons/power')['default']
    PixelarticonsZap: typeof import('~icons/pixelarticons/zap')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharedSubtitle: typeof import('./components/SharedSubtitle.vue')['default']
  }
}
