// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HighlightedText: typeof import('./components/HighlightedText.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    PixelarticonsPower: typeof import('~icons/pixelarticons/power')['default']
    PixelarticonsZap: typeof import('~icons/pixelarticons/zap')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
